name: dev-doh-frontend-info
services:
  app-dev:
    image: dev-doh-frontend-info:dev
    container_name: dev-doh-frontend-info
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - ${PORT:-3000}:3000
    restart: unless-stopped

networks:
  default:
    name: dev-doh-network
volumes:
  next_build_cache: null